### ISSUE TITLE
cli-client: "Unable to send OTR message without client ID"

### ISSUE THREAD

**Issue by mooware** [wireapp/wire-web-packages#470]
I tried to use the wire-cli script as described, but when I try to send a message, nothing happens. There's no error, and there's no message in the conversation.

The debugger tells me that `account.service.conversation.sendTextMessage()` returns `{ [[PromiseStatus]]: 'rejected', [[PromiseValue]]: Error: Unable to send OTR message without client ID.` at https://github.com/wireapp/wire-web-packages/blob/1c47e38809a4717640617bbea4545f1ce3203a75/packages/cli-client/src/main/index.ts#L81

Also, the script prints this to the console when it starts:
`Connected to Wire — User ID "<removed>" — Client ID "undefined"`

I suppose the Client ID should be defined somewhere?

**Comment by mooware** [comment]
I did some debugging, and it seems that the Client ID is lost somewhere around here: https://github.com/wireapp/wire-web-packages/blob/1c47e38809a4717640617bbea4545f1ce3203a75/packages/core/src/main/Account.ts#L388-L392

`getLocalClient()` returns the client data with ID, and `getClient(loadedClient.id)` also returns the client data including ID, but then that data isn't used. Instead it is expected that `apiClient.context!.clientId` contains the ID, but I don't see that this would ever be set anywhere. The context is apparently always initialized with `clientId = undefined`.

I also noticed another (unrelated) issue: when using `account.login()` in the main script instead of (or before) `account.listen()`, then the `ClientInfo` parameter isn't used if there is already any locally stored client. That's quite inconvenient when I want to use my own client name (or "model").

**Comment by bennyn** [comment]
Thanks @mooware for your very detailed report, highly appreciated! 😃 

We just released "@wireapp/cli-client v1.3.52" which should resolve the `sendTextMessage` bug. 

We also addressed your `account.login()` suggestion and decided to seperate `account.login` from `account.listen`. This change requires that you need to call `login` before `listen` in order to get a connection with Wire's WebSocket server. 

**Here is an example:**

https://github.com/wireapp/wire-web-packages/blob/e8f73d92f86d3c38e80794f1783a01b6cace078b/packages/travis-bot/src/main/index.ts#L82-L84

**Comment by mooware** [comment]
Works now, thanks!
